#pragma once
#include <Winsock2.h>
#include <stdlib.h>
#include <stdio.h>
#include "LogInfo.h"
#include "inih\ini.h"

#define APP_CONFIG_KEY			"Software\\PwnyPot\\Applications\\"
#define MAIN_CONFIG_KEY			"Software\\PwnyPot"
#define MATCH_CONF(s, n)		_stricmp(s, n) == 0

typedef struct _PWNYPOTREGCONFIG
{
	BOOL PROCESS_HOOKED;						// IMPLEMENTED
	BOOL SKIP_HBP_ERROR;						// IMPLEMENTED
	DWORD INIT_DELAY;							// IMPLEMENTED
	DWORD APP_ID;								// IMPLEMENTED
	CHAR LOG_PATH[MAX_PATH];					// IMPLEMENTED
    CHAR DBG_LOG_PATH[MAX_PATH];				// IMPLEMENTED
#ifndef CUCKOO    
	CHAR APP_PATH_HASH[MAX_PATH];   			// IMPLEMENTED
	CHAR APP_PATH[MAX_PATH];					// IMPLEMENTED
	CHAR PWNYPOT_MODULE_PATH[MAX_PATH];			// IMPLEMENTED
#else
	CHAR RESULT_SERVER_IP[MAX_PATH];			// IMPLEMENTED
	DWORD RESULT_SERVER_PORT;					// IMPLEMENTED
	CHAR CUCKOO_PIPE_NAME[MAX_PATH];			// IMPLEMENTED
	CHAR CUCKOO_ANALYZER_DIR[MAX_PATH];			// IMPLEMENTED
	CHAR DLL_PATH[MAX_PATH];			// IMPLEMENTED
#endif

	struct {
		CHAR ETA_MODULE[MAX_MODULE_NAME32];		// IMPLEMENTED
		BOOL ALLOW_MALWARE_DOWNLOAD;			// IMPLEMENTED
		BOOL KILL_SHELLCODE;					// IMPLEMENTED
		BOOL DUMP_SHELLCODE;					// IMPLEMENTED
		BOOL ETA_VALIDATION;					// IMPLEMENTED
		BOOL SYSCALL_VALIDATION;
		BOOL ANALYSIS_SHELLCODE;				// IMPLEMENTED
	} SHELLCODE;

	struct {
		BOOL DETECT_ROP;						// IMPLEMENTED
		BOOL KILL_ROP;							// IMPLEMENTED
		BOOL CALL_VALIDATION;
		BOOL FORWARD_EXECUTION;
		DWORD FE_FAR;
		BOOL STACK_MONITOR;						// IMPLEMENTED
		BOOL PIVOT_DETECTION;
		DWORD PIVOT_TRESHOLD;
		DWORD PIVOT_INST_TRESHOLD;				
		BOOL DUMP_ROP;							// IMPLEMENTED
		BOOL MAX_ROP_INST;						// IMPLEMENTED
		BOOL MAX_ROP_MEM;						// IMPLEMENTED
		DWORD ROP_MEM_FAR;						// IMPLEMENTED
	} ROP;

	struct {
		BOOL TEXT_RWX;
		BOOL STACK_RWX;							// IMPLEMENTED
		BOOL TEXT_RANDOMIZATION;
	} MEM;

	struct {
		PCHAR HEAP_SPRAY_ADDRESSES;				// IMPLEMENTED
		BOOL HEAP_SPRAY;						// IMPLEMENTED
		BOOL NULL_PAGE;							// IMPLEMENTED
		BOOL SEHOP;								// IMPLEMENTED
		BOOL SEHOP_SIMPLE;						// IMPLEMENTED
		BOOL FORCE_SEHOP;						// IMPLEMENTED
		BOOL PERMANENT_DEP;						// IMPLEMENTED
		BOOL ALLOW_MALWARE_EXEC;				// IMPLEMENTED
	} GENERAL;

} PWNYPOTREGCONFIG, *PPWNYPOTREGCONFIG;

extern PWNYPOTREGCONFIG PWNYPOT_REGCONFIG;

extern HMODULE hGlobalDllHandle;

#ifndef CUCKOO
STATUS
ParseRegConfig(
	OUT PPWNYPOTREGCONFIG pPwnyPotRegConfig,
	IN PCHAR szAppPathHash,
	IN DWORD Size
	);
#else
STATUS
ParseConfig(
	OUT PPWNYPOTREGCONFIG pPwnyPotRegConfig
	);
#endif